NAME: dance_vae # Experiment name
DEBUG: False 
ACCELERATOR: 'gpu' 
DEVICE: [0,1,2,3,4,5,6,7] 

# Training configuration
TRAIN:
  #---------------------------------
  STAGE: vae 
  ABLATION:
    SKIP_CONNECT: True
    PE_TYPE: mld
    DIFF_PE_TYPE: mld
  DATASETS: ['choreospectrum3d'] # Training datasets
  NUM_WORKERS: 4 
  BATCH_SIZE: 128 
  START_EPOCH: 0 
  END_EPOCH: 6000 # End epoch
  RESUME: '' 
  PRETRAINED_VAE: ''
  OPTIM:
    TYPE: AdamW # Optimizer type
    LR: 1e-4 # Learning rate

# Evaluating Configuration
EVAL:
  DATASETS: ['choreospectrum3d'] # Evaluating datasets
  BATCH_SIZE: 32 # Evaluating Batch size
  SPLIT: test

# Test Configuration
TEST:
  CHECKPOINTS: '' # Pretrained model path
  DATASETS: ['choreospectrum3d'] # training datasets
  SPLIT: test
  BATCH_SIZE: 32 # training Batch size
  MEAN: False
  NUM_SAMPLES: 1
  FACT: 1

# Datasets Configuration
DATASET:
  JOINT_TYPE: 'humanml3d' # join type
METRIC:
  TYPE: ['TemosMetric']
# Losses Configuration
LOSS:
  TYPE: enchant # Losses type
  LAMBDA_LATENT: 1.0e-5 # Lambda for latent Losses
  LAMBDA_KL: 1.0e-4 # Lambda for kl Losses
  LAMBDA_REC: 1.0 # Lambda for reconstruction Losses
  LAMBDA_CROSS: 1.0 # Lambda for reconstruction Losses
  LAMBDA_PRIOR: 0.0
  DIST_SYNC_ON_STEP: False 

# Model Configuration
model:
  vae: true # whether vae model
  model_type: enchant # model type
  condition: 'music'
  latent_dim: [1, 256] # latent dimension
  ff_size: 1024 #
  num_layers: 9 # number of layers
  num_head: 4 # number of head layers
  droupout: 0.1 # dropout rate
  activation: gelu # activation type
  guidance_scale: 7.5 #
  guidance_uncondp: 0.1 # 0.1 0.25

# Logger configuration
LOGGER:
  SACE_CHECKPOINT_EPOCH: 200
  LOG_EVERY_STEPS: 1
  VAL_EVERY_STEPS: 200
  TENSORBOARD: True
  WANDB:
    PROJECT: null
    OFFLINE: False
    RESUME_ID: null
